### ISSUE TITLE
SQL Error when using pgsql and groufolders

### ISSUE THREAD

**Issue by neumantm** [nextcloud-gmbh/mtime_fixer_tool_kit#14]
For me `solvable_files.sh` fails with 
```
ERROR:  syntax error at or near "base64"
LINE 4: ...mdzdGVjaG5pay9mdy1kdF9LYXBpdGVsMDhfMDFfMjAucGRm, 'base64'), ...
                                                             ^
```

I'm using pgsql and have groupfolders.

The error seems to occur in the groupfolder branch.

There ([line 73](https://github.com/nextcloud-gmbh/mtime_fixer_tool_kit/blob/8f1d949212d1ed29815e842eeccd5913e58b3ecc/solvable_files.sh#L73)) the quoting of the SQL statetment seems wrong to me. It is definitively different than the [version for normal users](https://github.com/nextcloud-gmbh/mtime_fixer_tool_kit/blob/8f1d949212d1ed29815e842eeccd5913e58b3ecc/solvable_files.sh#L104). 

After changing the quoting to be similar to the case for normal users, I don't get any errors anymore.

**Comment by artonge** [comment]
Thanks for reporting, can you confirm that this PR solved it for you: https://github.com/nextcloud-gmbh/mtime_fixer_tool_kit/pull/15

**Comment by neumantm** [comment]
Ah sorry, didn't see your comment/PR in time.
As your PR is exactly the same as mine: Yes that fixes it.

**Comment by artonge** [comment]
I merged yours as you put more information in the PR, thanks again :)
