### ISSUE TITLE
PostgreSQL support broken.

### ISSUE THREAD

**Issue by wscheicher** [nextcloud-gmbh/mtime_fixer_tool_kit#19]
The Commandline to call psql in solvable_files.sh seems to be quite broken.
It for example contains: `-E 'UTF-8'`, which looks like a attempt to set the encoding, however man psql states:
```
       -E
       --echo-hidden
           Echo the actual queries generated by \d and other backslash commands.
           You can use this to study psql's internal operations.
           This is equivalent to setting the variable ECHO_HIDDEN to on.

```

Also the way the connect string is put together doesn't seem to allow connecting via socket.

I was able to get the script to work by replacing `"postgresql://$db_user:$db_pwd@$db_host/$db_name"` with just the name of the database and completely removing `-E 'UTF-8'`.

**Comment by artonge** [comment]
Introduced by https://github.com/nextcloud-gmbh/mtime_fixer_tool_kit/pull/5

@matthieugallien should we revert that for pgsql?
@wscheicher could you maybe make a PR?
