### ISSUE TITLE
Fixing mtime issue on Nextcloud instances with S3 as primary storage

### ISSUE THREAD

**Issue by kylespencer** [nextcloud-gmbh/mtime_fixer_tool_kit#39]
The documentation is not clear about how to handle Nextcloud instances that use S3 as primary storage. 

According to Nextcloud's documentation, in such cases, file metadata is stored entirely in the database. However, the solvable_files.sh script expects a local data directory and seems to only address afflicted files that exist in both the data directory and database.

When using S3 as primary storage, there is no local data directory, so the script does not identify or address any files.

Is there a workaround for this?

**Comment by artonge** [comment]
Hello,

It is indeed not possible to recover the mtime from S3 buckets with this tool.

I remember that some S3 providers store the write date of the files, so it should be possible to restore it from there.
