### ISSUE TITLE
Browsing issue

### ISSUE THREAD

**Issue by Delurkdotcom** [nextcloud-gmbh/mtime_fixer_tool_kit#8]
Hi,

The task browses a single user folder and then stops. it does'nt browse the __groupfolders folder.

**Comment by artonge** [comment]
Hello @Delurkdotcom,

Can you be more specific?

**Comment by Delurkdotcom** [comment]
In the data folder, I have several users and a shared folder named __groupfolders.
When I run the task with the list parameter, only the first folder of the first user is browsed.

**Comment by artonge** [comment]
Can you give me the command you run and the output ?

**Comment by Delurkdotcom** [comment]
```
# ./solvable_files.sh /mnt/ncdata mysql 172.16.0.154 ncuser pass ncdb list noscan > mtimelist_script.log
# cat mtimelist_script.log
/mnt/ncdata/Delurkdotcom/files/Documents/picture1
[...]
/mnt/ncdata/Delurkdotcom/files/Documents/picture99

# cat mtimelist_script.log | wc -l
112
```

But if I list all the files which are corrupted by the bug in the main data folder using find
```
# cd /mnt/ncdata
# find . -printf '%T@ %t %p\n' | sort -k 1 -n | cut -d' ' -f2- | grep ' 1970 '  | wc -l
196
```

there is 84 files in the __groupdolfers which are ignore by your script.

**Comment by artonge** [comment]
Should get fixed by https://github.com/nextcloud-gmbh/mtime_fixer_tool_kit/pull/9

Thanks for reporting :)
